mytestapp/config/routes.rb
Mytestapp::Application.routes.draw do
  resources :user_credits

  resources :orders

  resources :items

  resources :categories

  resources :profiles

  resources :users

  get '/login' => 'users#login', as: 'login'
  post '/loginuser' => 'users#loginuser', as: 'loginuser'
  delete '/logout' => 'users#logout', as: 'logout'
  get '/profile_create' => 'profiles#edit', as: 'profile_create'
  get '/category_filter' => 'items#category_filter', as: 'category_filter'
  get 'purchase/:id' => 'items#purchase', as: 'purchase'
  match 'purchase_option' => 'items#purchase_option', via: [:PATCH]

   root 'users#index'

end

mytestapp/app/models/user.rb
class User < ActiveRecord::Base
	validates_presence_of :user_name,:password, :password_confirmation, :user_email
	validates :user_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
	has_one :profile
	has_many :categories
	attr_accessor :password_confirmation
end

mytestapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.paginate(:page => params[:page], :per_page => 5)
   
  end
  # GET /users/1
  # GET /users/1.json
  def show
  end
  
  def login
    @user = User.new
  end

  def loginuser
    @user=User.where("user_email=? AND password=?",params[:user][:user_email],params[:user][:password]).last
    unless @user.nil?
      session[:user]=@user
      flash[:notice] = "Login successfully"
      redirect_to :action => "index"
    else
      flash[:notice]="Email password not matched"
      redirect_to :action => "login"
    end
   
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        @profile = Profile.create!(user_id:@user.user_id)
        format.html { redirect_to :login, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.profile.destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def logout
    session[:user] = nil
    flash[:notice] = "You are now logged out"
    redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_id, :user_name, :user_email, :password, :user_type, :password_confirmation)
    end
end

mytestapp/app/helpers/users_helper.rb
module UsersHelper
end

mytestapp/app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  
  <div class="control-group">
    <%= f.label :user_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, :class => 'control-label' %>
    <div class="controls">
   <%= f.password_field :password_confirmation, :class => 'text_field'%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :user_type, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary', :onclick => "return validateform();" %>
    <%#= f.submit_tag , :onclick => "return validateform();" %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>
<script type="text/javascript">


  function validateform() {
    var pwd=$("#user_password").val();
    var cpwd=$("#user_password_confirmation").val();
    if (pwd.length < 7){
      alert( "The password is too short: it must at least 8 characters.")
      return false
    }
    if (pwd==cpwd)
    {
      return true
    }
    else{
      alert("The passwords you typed do not match. Type the new password in both text boxes.")
      return false

    }
  }
</script>

mytestapp/app/views/users/_user.html.erb
<%- model_class = User -%>
<table class="table table-striped">
  <thead>
    <tr>
    <th><%= model_class.human_attribute_name(:Number) %></th>
      <th><%= model_class.human_attribute_name(:user_name) %></th>
      <th><%= model_class.human_attribute_name(:user_email) %></th>
      <th><%= model_class.human_attribute_name(:usertype) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%i=0%>
    <% !@users.nil? && @users.each do |user| %>
      <tr>
        <td><%=i=i+1%></td>
        <td><%= link_to user.user_name, user_path(user) %></td>
        <td><%= user.user_email %></td>
        <%pvalue=Profile.find_by_user_id(user.user_id)%>
        <td><%#= link_to "Profile", profile_path(pvalue.id)%><%= user.user_type %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div><%= will_paginate @users %><div>

mytestapp/app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

mytestapp/app/views/users/index.html.erb
<%- model_class = User -%>
<%#=session[:user].user_name if !session[:user].nil? %>
<%#=current_user.categories.inspect%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>
            </div>
<div id="home_start" style="width:100%;">
        <%= render :partial=>"user" %>
</div>



<script type="text/javascript">
  $(function(){
     $('.pagination a').attr('data-remote', 'true')
  });
</script>

mytestapp/app/views/users/index.js.erb
$('#home_start').html('<%= escape_javascript(render(:partial => 'user')) %>');

mytestapp/app/views/users/login.html.erb
<div class="page-header">
  <h1>Login</h1>
</div>
<%= form_for @user, :url => {:action => "loginuser"}, :html => { :class => 'form-horizontal' } do |f| %>

  
  <div class="control-group">
    <%= f.label :user_email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>
 
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary'%>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>
<script type="text/javascript">


</script>

mytestapp/app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

mytestapp/app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_name) %>:</strong></dt>
  <dd><%= @user.user_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_email) %>:</strong></dt>
  <dd><%= @user.user_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_type) %>:</strong></dt>
  <dd><%= @user.user_type %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>