mytestapp/config/routes.rb
Mytestapp::Application.routes.draw do
  resources :user_credits

  resources :orders

  resources :items

  resources :categories

  resources :profiles

  resources :users

  get '/login' => 'users#login', as: 'login'
  post '/loginuser' => 'users#loginuser', as: 'loginuser'
  delete '/logout' => 'users#logout', as: 'logout'
  get '/profile_create' => 'profiles#edit', as: 'profile_create'
  get '/category_filter' => 'items#category_filter', as: 'category_filter'
  get 'purchase/:id' => 'items#purchase', as: 'purchase'
  match 'purchase_option' => 'items#purchase_option', via: [:PATCH]

   root 'users#index'

end

mytestapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mytestapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div align="center">
  <div>
  <%#=admin.inspect if current_user && admin%>
  	<% if !current_user.nil? %>
  	Welcome <%= current_user.user_name %> <%= link_to "Sign out", logout_path, :method => :delete %>
  	 <%pvalue=Profile.find_by_user_id(current_user.user_id)%>
     <strong><%= link_to "Home", root_path%></strong>
  	 <strong><%= link_to "Profile", profile_path(pvalue.id)%></strong>
     <strong><%= link_to "Products", items_path%></strong>
  	
      <% else %>
         <%= link_to "Sign in", login_path %>	
      <% end %>
  </div>
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

mytestapp/app/views/layouts/mynewapp.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mytestapp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Mytestapp</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>